- hosts: localhost
  environment:
    PATH: "{{ ansible_env.PATH }}:~/.local/bin/"
  tasks:
  - name: update-cache
    apt:
      name: "*"
      state: latest
      update_cache: yes
    become: yes
  - name: full-upgrade
    apt:
      upgrade: full
      autoclean: yes
      autoremove: yes
    become: yes
  - name: Install dependency packages
    apt:
      name: 
      - git
      - wget
      - curl
      - net-tools
      - unattended-upgrades
      - software-properties-common
      - python3
      - python3-apt
      - python3-distutils
      - python-is-python3
      - vim
      - kde-plasma-desktop
      state: latest
    become: yes
  - name: Install Chrome
    apt:
      deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - name: Test for vim in EDITOR
    shell: 
      cmd: "grep 'export EDITOR=vim' ~/.bashrc"
    register: test_vim_editor
    failed_when: "test_vim_editor.rc > 1"
    changed_when: false
  - name: add pip bin to bashrc
    lineinfile:
      dest: ~/.bashrc
      line: "export EDITOR=vim"
    when: test_vim_editor.rc != "0"
  - name: Copy .vimrc
    ansible.builtin.copy:
      src: .vimrc
      dest: ~/.vimrc
  - name: Copy .gitignore
    ansible.builtin.copy:
      src: .gitignore
      dest: ~/.gitignore
  - name: Test for pip in PATH
    shell: 
      cmd: "grep 'export PATH=${PATH}:${HOME}/.local/bin' ~/.bashrc"
    register: test_pip_path
    failed_when: "test_pip_path.rc > 1"
    changed_when: false
  - name: add pip bin to bashrc
    lineinfile:
      dest: ~/.bashrc
      line: "export PATH=${PATH}:${HOME}/.local/bin"
    when: test_pip_path.rc != "0"
  - name: Install pip
    shell: |
      curl https://bootstrap.pypa.io/get-pip.py -o /tmp/get-pip.py
      python /tmp/get-pip.py --user
    args:
      creates: ~/.local/bin/pip
  - name: Install global pip
    shell: |
      curl https://bootstrap.pypa.io/get-pip.py -o /tmp/get-pip.py
      sudo python /tmp/get-pip.py
    become: yes
    args:
      creates: /usr/local/bin/pip
  - name: Install pip packages
    pip: 
      name: 
        - ipython
        - ansible
