- hosts: piholes
  tasks:
  - name: /boot/config.txt
    ansible.builtin.copy:
      src: boot_config.txt
      dest: /boot/config.txt
      owner: root
      group: root
      mode: 0755
    become: yes
  - name: update-cache
    apt:
      name: "*"
      state: latest
      update_cache: yes
    become: yes
  - name: full-upgrade
    apt:
      upgrade: full
      autoclean: yes
      autoremove: yes
    become: yes
  - name: Install dependency packages
    apt:
      name:
      - git
      - wget
      - curl
      - net-tools
      - unattended-upgrades
      - python3
      - python3-distutils
      - python3-pip
      - vim
      - build-essential
      state: latest
    become: yes
  - name: Python3
    file:
      src: "/usr/bin/python3"
      path: "/usr/bin/python"
      state: link
    become: yes
  - name: Add user
    user:
      name: "{{ remote_username }}"
    become: yes
# TODO: Automate the actual install, but since I'm putting this in people's homes...
